#!/usr/bin/env bash
# ccstatusline-wrapper.sh - Extract context % and make it available to tools
#
# This wrapper:
# 1. Receives JSON from Claude Code via stdin
# 2. Extracts context_percentage and session_id
# 3. Stores in session-specific file for tools to source
# 4. Passes JSON through to ccstatusline
#
# Usage in .claude/settings.json:
# {
#   "statusLine": {
#     "type": "command",
#     "command": ".bitbot/scripts/ccstatusline-wrapper/wrapper.sh"
#   }
# }

set -euo pipefail

# Read JSON from stdin
JSON_DATA=$(cat)

# Extract session_id (pure bash regex)
if [[ "$JSON_DATA" =~ \"session_id\":\"([^\"]+)\" ]]; then
    SESSION_ID="${BASH_REMATCH[1]}"
else
    SESSION_ID="unknown"
fi

# Extract context percentage (pure bash regex)
if [[ "$JSON_DATA" =~ \"context_percentage\":([0-9.]+) ]]; then
    CONTEXT_PCT="${BASH_REMATCH[1]}"
else
    CONTEXT_PCT="0"
fi

# Store in session-specific env file
# Tools can source: .bitbot/session-env/<session-id>.env
ENV_DIR="${CLAUDE_PROJECT_DIR:-.}/.bitbot/session-env"
mkdir -p "$ENV_DIR"
ENV_FILE="$ENV_DIR/${SESSION_ID}.env"

# Write env file atomically (tmp + mv)
TMP_FILE="${ENV_FILE}.tmp.$$"
cat > "$TMP_FILE" << EOF
# Claude Code session environment
# Auto-generated by ccstatusline-wrapper
# Session: $SESSION_ID
export CLAUDE_CONTEXT_PCT='$CONTEXT_PCT'
export CLAUDE_SESSION_ID='$SESSION_ID'
EOF
mv "$TMP_FILE" "$ENV_FILE"

# Pass through to ccstatusline
if command -v ccstatusline &>/dev/null; then
    echo "$JSON_DATA" | ccstatusline
else
    # Simple fallback
    echo "[Claude] Context: ${CONTEXT_PCT}%"
fi
