#!/usr/bin/env bash
# statusline-wrapper.sh - Extract context % and make it available to tools
#
# This wrapper:
# 1. Receives JSON from Claude Code via stdin
# 2. Extracts context_percentage and session_id
# 3. Stores in session-specific file for tools to source
# 4. Passes JSON through to status line tool (e.g., ccstatusline)
#
# Usage in .claude/settings.json:
# {
#   "statusLine": {
#     "type": "command",
#     "command": "/workspace/.bitbot/internal/container/bitbot/wrapper/statusline-wrapper/wrapper.sh"
#   }
# }
#
# Note: Lives in /container/bitbot/wrapper/ (repository)
# Copied to .bitbot/internal/container/bitbot/wrapper/ during `bitbot init`
# Accessed in container via workspace mount

set -euo pipefail

# Read JSON from stdin
JSON_DATA=$(cat)

# Extract session_id (pure bash regex)
if [[ "$JSON_DATA" =~ \"session_id\":\"([^\"]+)\" ]]; then
    SESSION_ID="${BASH_REMATCH[1]}"
else
    SESSION_ID="unknown"
fi

# Extract context percentage (pure bash regex)
if [[ "$JSON_DATA" =~ \"context_percentage\":([0-9.]+) ]]; then
    CONTEXT_PCT="${BASH_REMATCH[1]}"
else
    CONTEXT_PCT="0"
fi

# Determine context icon for display
CONTEXT_INT=$(printf "%.0f" "$CONTEXT_PCT")
if [ "$CONTEXT_INT" -lt 50 ]; then
    CONTEXT_ICON="🟢"
elif [ "$CONTEXT_INT" -lt 70 ]; then
    CONTEXT_ICON="🟡"
elif [ "$CONTEXT_INT" -lt 85 ]; then
    CONTEXT_ICON="🟠"
else
    CONTEXT_ICON="🔴"
fi

# Store in session-specific env file
# Tools can source: .bitbot/session-env/<session-id>.env
ENV_DIR="${CLAUDE_PROJECT_DIR:-.}/.bitbot/session-env"
mkdir -p "$ENV_DIR"
ENV_FILE="$ENV_DIR/${SESSION_ID}.env"

# Write env file atomically (tmp + mv)
TMP_FILE="${ENV_FILE}.tmp.$$"
cat > "$TMP_FILE" << EOF
# Claude Code session environment
# Auto-generated by statusline-wrapper
# Session: $SESSION_ID
export CLAUDE_CONTEXT_PCT='$CONTEXT_PCT'
export CLAUDE_SESSION_ID='$SESSION_ID'
export CLAUDE_CONTEXT_ICON='$CONTEXT_ICON'
EOF
mv "$TMP_FILE" "$ENV_FILE"

# Pass through to status line tool (if available)
if command -v ccstatusline &>/dev/null; then
    echo "$JSON_DATA" | ccstatusline
else
    # Simple fallback display with color indicator
    echo "${CONTEXT_ICON} Context: ${CONTEXT_PCT}%"
fi
